-- Created by Ebean DDL
-- To stop Ebean DDL generation, remove this comment (both lines) and start using Evolutions

-- !Ups

-- apply changes
create table todo (
  id                            bigint generated by default as identity not null,
  content                       varchar(255),
  done                          boolean default false not null,
  constraint pk_todo primary key (id)
);


-- !Downs

-- drop all
drop table if exists todo;

